/* This file is generated by tis-mkfs tool only the first time.
It may be modified to adjust parameters. It won't be erased.
It can be removed to restore the default values. */

/* Default values for uid, gid, etc.
* Use the macros below to give other values
* or redefine the __TIS_MKFS_xxx from the command line. For instance:
* $ tis-analyzer -D __TIS_MKFS_UID=1234 ...
*/
#define TIS_uid  __TIS_MKFS_UID
#define TIS_euid __TIS_MKFS_EUID
#define TIS_gid  __TIS_MKFS_GID
#define TIS_egid __TIS_MKFS_EGID

/* The file and directory owner: */
#define TIS_FILE_UID __TIS_MKFS_FILE_UID
#define TIS_FILE_GID __TIS_MKFS_FILE_GID

/* TIS_FILE_MODE defines the default permission for the files.
*/
#define TIS_FILE_MODE (S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)

/* TIS_FILE_SIZE is the default size for unknown files.
* You can change it here, or initilize it from you main function.
* For instance, to give a size between 100 and 200 to the 'unknown.txt' file:
*
* int i = __mkfs_get_file ("unknown.txt");
* assert (i != -1);
* __mkfs_fs_files[i].__mkfs_stat->st_size = tis_interval (100, 200);
*/
#define TIS_FILE_SIZE 100
